name: Build & Deploy
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
      with:
        cache-on-failure: true
      
    - name: Setup Dioxus Cli
      run: cargo install dioxus-cli --locked
      
    - name: Setup TailwindCSS Cli
      run: npm -g install tailwindcss

    - name: Refresh TailwindCSS
      run: npx tailwindcss -c tailwind.config.js -i ./src/index.css -o ./public/tailwind.css

    - name: Run Dioxus
      run: dx build --release
    
    - name: Remove leading slash from paths
      run: sed -i 's|/./assets/dioxus/|./assets/dioxus/|' dist/index.html

    - name: Upload
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: dist

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}